import pizzaImage from '../assets/images/products/pizza.svg';

//ProductId:'1Far2Piz8', :- id,name 3 later,How many Category,category[0] 3 later,
export const MirchMasalaProduct = [
    {
        id: 1,
        ProductId:'101',
        name: 'Farmhouse Pizza',
        title: 'Freshness in Every Bite!',
        description: 'Delicious Farmhouse Pizza with a perfect blend of veggies. Available in 8 inch for Rs 159 and 10 inch for Rs 199.',
        originalPrice: 200,
        discountedPrice: 159,
        rating: 4.5,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Pizza', '8 inch', 'Farmhouse'],
        variableProductsId: [1, 2],
        spacel: 'New Arrivals',
        available: true,
        category: ['Pizza', '8 inch', 'New Arrivals'],
        deal: 'sale',
    },
    {
        id: 2,
        ProductId:'102',
        name: 'Farmhouse Pizza',
        title: 'Family Size Delight!',
        description: 'Enjoy our Family Size Farmhouse Pizza, loaded with goodness. 10 inch for Rs 199 - Limited time offer!',
        originalPrice: 250,
        discountedPrice: 199,
        rating: 4.5,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Pizza', '10 inch', 'Farmhouse'],
        variableProductsId: [1, 2],
        spacel: 'New Arrivals',
        available: true,
        category: ['Pizza', '10 inch', 'New Arrivals'],
        deal: 'Best Sale',
    },
    {
        id: 3,
        ProductId:'103',
        name: 'Mushroom Pizza',
        title: 'Savor the Earthy Flavors!',
        description: 'Indulge in the earthy goodness of Mushroom Pizza. 8 inch for Rs 169 - Irresistible taste!',
        originalPrice: 110,
        discountedPrice: 169,
        rating: 4.5,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Pizza', '8 inch', 'Mushroom'],
        variableProductsId: [3, 4],
        spacel: 'New Arrivals',
        available: true,
        category: ['Pizza', '8 inch','New Arrivals'],
        deal: 'deal',
    },
    {
        id: 4,
        ProductId:'104',
        name: 'Mushroom Pizza',
        title: 'Deliciously Earthy!',
        description: 'Savor the earthy goodness with our Mushroom Pizza. 10 inch for Rs 209 - A delight for mushroom lovers!',
        originalPrice: 290,
        discountedPrice: 209,
        rating: 4.4,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Pizza', '10 inch', 'Mushroom'],
        variableProductsId: [3, 4],
        spacel: 'New Arrivals',
        available: true,
        category: ['Pizza', '10 inch', 'New Arrivals'],
        deal: 'sale',
    },
    {
        id: 5,
        ProductId:'105',
        name: 'Peri Peri Paneer Pizza',
        title: 'Spice it Up with Paneer!',
        description: 'Indulge in the spicy delight of Peri Peri Paneer Pizza. 8 inch for Rs 169 and 10 inch for Rs 219.',
        originalPrice: 180,
        discountedPrice: 169,
        rating: 4.2,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Pizza', '8 inch', 'Peri Peri Paneer'],
        variableProductsId: [5, 6],
        spacel: '',
        available: true,
        category: ['Pizza', '8 inch'],
        deal: 'sale',
    },
    {
        id: 6,
        ProductId:'106',
        name: 'Peri Peri Paneer Pizza',
        title: 'Bold Flavors for Pizza Lovers!',
        description: 'Try our bold and flavorful Peri Peri Paneer Pizza. 10 inch for Rs 219 - Limited stock!',
        originalPrice: 230,
        discountedPrice: 219,
        rating: 4.3,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Pizza', '10 inch', 'Peri Peri Paneer'],
        variableProductsId: [5, 6],
        spacel: '',
        available: true,
        category: ['Pizza', '10 inch', 'BEST SELLERS'],
        deal: 'Best Sale',
    },
    {
        id: 7,
        ProductId:'107',
        name: 'Paneer Tikka Pizza',
        title: 'Paneer Perfection!',
        description: 'Indulge in the perfection of Paneer Tikka Pizza. 8 inch for Rs 179 and 10 inch for Rs 229 - A Paneer lover’s delight!',
        originalPrice: 200,
        discountedPrice: 179,
        rating: 4.6,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Pizza', '8 inch', 'Paneer Tikka'],
        variableProductsId: [7, 8],
        spacel: '',
        available: true,
        category: ['Pizza', '8 inch'],
        deal: 'sale',
    },
    {
        id: 8,
        ProductId:'108',
        name: 'Paneer Tikka Pizza',
        title: 'Spicy & Flavorful!',
        description: 'Experience the spice and flavor of our Paneer Tikka Pizza. 10 inch for Rs 229 - Order now!',
        originalPrice: 250,
        discountedPrice: 229,
        rating: 4.5,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Pizza', '10 inch', 'Paneer Tikka', 'Mashroom'],
        variableProductsId: [7, 8],
        spacel: '',
        available: true,
        category: ['Pizza', '10 inch', 'BEST SELLERS'],
        deal: '',
    },
    {
        id: 9,
        ProductId:'109',
        name: 'Paneer Makhni Pizza',
        title: 'Buttery Goodness!',
        description: 'Savor the buttery goodness of Paneer Makhni Pizza. 8 inch for Rs 179 and 10 inch for Rs 229 - A rich and indulgent treat!',
        originalPrice: 200,
        discountedPrice: 179,
        rating: 4.7,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Pizza', '8 inch', 'Paneer Makhni'],
        variableProductsId: [9, 10],
        spacel: '',
        available: true,
        category: ['Pizza', '8 inch'],
        deal: 'Best Sale',
    },
    {
        id: 10,
        ProductId:'110',
        name: 'Paneer Makhni Pizza',
        title: 'Creamy & Irresistible!',
        description: 'Indulge in the creamy and irresistible flavor of Paneer Makhni Pizza. 10 inch for Rs 229 - Limited stock!',
        originalPrice: 250,
        discountedPrice: 229,
        rating: 4.8,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Pizza', '10 inch', 'Paneer Makhni'],
        variableProductsId: [9, 10],
        spacel: '',
        available: true,
        category: ['Pizza', '10 inch'],
        deal: 'sale',
    },
    {
        id: 11,
        ProductId:'111',
        name: 'Schezwan Paneer Pizza',
        title: 'Spice Up Your Taste Buds!',
        description: 'Spice up your taste buds with our Schezwan Paneer Pizza. 8 inch for Rs 169 and 10 inch for Rs 219 - A fiery delight!',
        originalPrice: 190,
        discountedPrice: 169,
        rating: 4.4,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Pizza', '8 inch', 'Schezwan Paneer'],
        variableProductsId: [11, 12],
        spacel: 'Top Rated',
        available: true,
        category: ['Pizza', '8 inch', 'Top Rated', 'BEST SELLERS'],
        deal: '',
    },
    {
        id: 12,
        ProductId:'112',
        name: 'Schezwan Paneer Pizza',
        title: 'Fiery and Flavorful!',
        description: 'Experience the fiery and flavorful Schezwan Paneer Pizza. 10 inch for Rs 219 - Limited time offer!',
        originalPrice: 240,
        discountedPrice: 219,
        rating: 4.6,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Pizza', '10 inch', 'Schezwan Paneer'],
        variableProductsId: [11, 12],
        spacel: 'Trending',
        available: true,
        category: ['Pizza', '10 inch', 'Trending'],
        deal: '',
    },
    {
        id: 13,
        ProductId:'113',
        name: 'Crispy Veggie Burger',
        title: 'Crunchy & Delicious!',
        description: 'Satisfy your cravings with our Crispy Veggie Burger. Only Rs 59 - A perfect snack!',
        originalPrice: 59,
        discountedPrice: 59,
        rating: 4.0,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Burger', 'Crispy Veggie'],
        variableProductsId: [13],
        spacel: 'Trending',
        available: true,
        category: ['Burger', 'Trending'],
        deal: '',
    },
    {
        id: 14,
        ProductId:'114',
        name: 'Crispy Veggie Cheese Burger',
        title: 'Cheese Lover`s Delight!',
        description: 'Savor the cheesy goodness with our Crispy Veggie Cheese Burger. Only Rs 79 - A treat for cheese enthusiasts!',
        originalPrice: 89,
        discountedPrice: 79,
        rating: 4.5,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Burger', 'Crispy Veggie Cheese'],
        variableProductsId: [14],
        spacel: 'Trending',
        available: true,
        category: ['Burger', 'Trending', 'BEST SELLERS'],
        deal: '',
    },
    {
        id: 15,
        ProductId:'115',
        name: 'Paneer Makhani Burger',
        title: 'A Symphony of Flavors!',
        description: 'Indulge in the symphony of flavors with our Paneer Makhani Burger. Only Rs 99 - A burger that delights!',
        originalPrice: 99,
        discountedPrice: 99,
        rating: 4.4,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Burger', 'Paneer Makhani'],
        variableProductsId: [15],
        spacel: 'Trending',
        available: true,
        category: ['Burger', 'Trending'],
        deal: '',
    },
    {
        id: 16,
        ProductId:'116',
        name: 'Party Special Combo',
        title: 'Celebrate with Veg Delights!',
        description: 'Make your celebration memorable with our Party Special Combo - Farmhouse Pizza, Crispy Veggie Burger, and more. Only Rs 259!',
        originalPrice: 280,
        discountedPrice: 259,
        rating: 4.9,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Combo', 'Party Veg'],
        variableProductsId: [16,17,18],
        spacel: 'Top Rated',
        available: true,
        category: ['Combo', 'Top Rated'],
        deal: 'sale',
    },
    {
        id: 17,
        ProductId:'117',
        name: 'Spicy Veg Combo',
        title: 'Heat up your Taste Buds!',
        description: 'Enjoy the heat with our Spicy Veg Combo - Farmhouse Pizza, Crispy Veggie Burger, and more. Only Rs 299!',
        originalPrice: 320,
        discountedPrice: 259,
        rating: 4.7,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Combo', 'Spicy Veg'],
        variableProductsId: [16,17,18],
        spacel: 'Top Rated',
        available: true,
        category: ['Combo', 'Top Rated'],
        deal: 'sale',
    },
    {
        id: 18,
        ProductId:'118',
        name: 'Makhni Combo',
        title: 'Indulge in Makhni Magic!',
        description: 'Experience the magic of Makhni with our Makhni Combo - Paneer Makhni Pizza, Makhni Burger, and more. Only Rs 259!',
        originalPrice: 280,
        discountedPrice: 259,
        rating: 4.8,
        images: [pizzaImage, pizzaImage],
        keyWords: ['Combo', 'Makhni'],
        variableProductsId: [16,17,18],
        spacel: 'Top Rated',
        available: true,
        category: ['Combo', 'Top Rated'],
        deal: 'sale',
    },
]