export const ProductsApi = [
    // 
    {
        id:1,
        spacel: `New Arrivals`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Relaxed Short full Sleeve T-Shirt`,
        showcaseCategory: `Clothes`,
        price: `$45.00`,
        del: `$12.00`,
    },
    {
        id:2,
        spacel: `New Arrivals`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Girls pnk Embro design Top`,
        showcaseCategory: `Clothes`,
        price: `$61.00`,
        del: `$9.00`,
    },
    {
        id:3,
        spacel: `New Arrivals`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Black Floral Wrap Midi Skirt`,
        showcaseCategory: `Clothes`,
        price: `$76.00`,
        del: `$25.00`,
    },
    {
        id:4,
        spacel: `New Arrivals`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Pure Garment Dyed Cotton Shirt`,
        showcaseCategory: `Mens Fashion`,
        price: `$68.00`,
        del: `$31.00`,
    },
    {
        id:5,
        spacel: `New Arrivals`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `MEN Yarn Fleece Full-Zip Jacket`,
        showcaseCategory: `Winter wear`,
        price: `$61.00`,
        del: `$11.00`,
    },
    {
        id:6,
        spacel: `New Arrivals`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Mens Winter Leathers Jackets`,
        showcaseCategory: `Winter wear`,
        price: `$32.00`,
        del: `$20.00`,
    },
    {
        id:7,
        spacel: `New Arrivals`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Mens Winter Leathers Jackets`,
        showcaseCategory: `Jackets`,
        price: `$50.00`,
        del: `$25.00`,
    },
    {
        id:8,
        spacel: `New Arrivals`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Better Basics French Terry Sweatshorts`,
        showcaseCategory: `Shorts`,
        price: `$20.00`,
        del: `$10.00`,
    },
    {
        id:9,
        spacel: `Trending`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Running & Trekking Shoes - White`,
        showcaseCategory: `Sports`,
        price: `$49.00`,
        del: `$15.00`,
    },
    {
        id:10,
        spacel: `Trending`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Trekking & Running Shoes - black`,
        showcaseCategory: `Sports`,
        price: `$78.00`,
        del: `$36.00`,
    },
    {
        id:11,
        spacel: `Trending`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Womens Party Wear Shoes`,
        showcaseCategory: `Party wear`,
        price: `$94.00`,
        del: `$42.00`,
    },
    {
        id:12,
        spacel: `Trending`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Sports Claw Women's Shoes`,
        showcaseCategory: `Sports`,
        price: `$54.00`,
        del: `$65.00`,
    },
    {
        id:13,
        spacel: `Trending`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Air Trekking Shoes - white`,
        showcaseCategory: `Sports`,
        price: `$52.00`,
        del: `$55.00`,
    },

    {
        id:14,
        spacel: `Trending`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Boot With Suede Detail`,
        showcaseCategory: `boots`,
        price: `$20.00`,
        del: `$30.00`,
    },
    {
        id:15,
        spacel: `Trending`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Men's Leather Formal Wear shoes`,
        showcaseCategory: `formal`,
        price: `$56.00`,
        del: `$78.00`,
    },
    {
        id:16,
        spacel: `Trending`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Casual Men's Brown shoes`,
        showcaseCategory: `Casual`,
        price: `$50.00`,
        del: `$55.00`,
    },{
        id:17,
        spacel: `Top Rated`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Pocket Watch Leather Pouch`,
        showcaseCategory: `Watches`,
        price: `$50.00`,
        del: `$34.00`,
    },
    {
        id:18,
        spacel: `Top Rated`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Silver Deer Heart Necklace`,
        showcaseCategory: `Jewellery`,
        price: `$84.00`,
        del: `$30.00`,
    },
    {
        id:19,
        spacel: `Top Rated`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Titan 100 Ml Womens Perfume`,
        showcaseCategory: `Perfume`,
        price: `$42.00`,
        del: `$10.00`,
    },
    {
        id:20,
        spacel: `Top Rated`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Men's Leather Reversible Belt`,
        showcaseCategory: `Belt`,
        price: `$24.00`,
        del: `$10.00`,
    },
    {
        id:21,
        spacel: `Top Rated`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `platinum Zircon Classic Ring`,
        showcaseCategory: `jewellery`,
        price: `$62.00`,
        del: `$65.00`,
    },
    {
        id:22,
        spacel: `Top Rated`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Smart watche Vital Plus`,
        showcaseCategory: `Watches`,
        price: `$56.00`,
        del: `$78.00`,
    },
    {
        id:23,
        spacel: `Top Rated`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `shampoo conditioner packs`,
        showcaseCategory: `cosmetics`,
        price: `$20.00`,
        del: `$30.00`,
    },
    {
        id:24,
        spacel: `Top Rated`,
        image: require(`../assets/images/products/pizza.svg`).default,
        showcaseTitle: `Rose Gold Peacock Earrings`,
        showcaseCategory: `jewellery`,
        price: `$20.00`,
        del: `$30.00`,
    },
    {
        id:25,
        spacel: `Top Rated`,
        image: require(`../assets/images/products/pizza.svg`).default,
        image: ``,
        showcaseTitle: ``,
        showcaseCategory: ``,
        price: ``,
        del: ``,
    },


]