import pizzaImage from '../assets/images/products/pizza.svg';

export const MainProducts = [
   {
        id: 1,
        category: 'jacket',
        keyWords:['jacket','jacket'],
        spacel: '',
        title: "Mens Winter Leathers Jackets",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        rating: 1.5,
        price: 48.00,
        originalPrice: 75.00,
        images: [pizzaImage,pizzaImage],
        badge: '15%',
    },
    {
        id: 2,
        category: 'shirt',
        keyWords:['shirt'],
        title: "Pure Garment Dyed Cotton Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        rating: 3.5,
        price: 45.00,
        originalPrice: 56.00,
        images: [pizzaImage,pizzaImage],
        badge: 'sale',
    },
    {
        id: 3,
        category: 'jacket',
        keyWords:['jacket'],
        title: "MEN Yarn Fleece Full-Zip Jacket",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        rating: 4,
        price: 58.00,
        originalPrice: 65.00,
        images: [pizzaImage,pizzaImage],
    },
    {
        id: 4,
        category: 'skirt',
        keyWords:['skirt'],
        title: "Black Floral Wrap Midi Skirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        rating: 3.5,
        price: 25.00,
        originalPrice: 35.00,
        images: [pizzaImage,pizzaImage],
        badge: 'new',
    },
    {
        id: 5,
        category: 'casual',
        keyWords:['casual'],
        title: "Casual Men's Brown shoes",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        rating: 3.5,
        price: 99.00,
        originalPrice: 105.00,
        images: [pizzaImage,pizzaImage],
        badge: 'new',
    },
    {
        id: 6,
        category: 'watches',
        keyWords:['watches'],
        title: "Pocket Watch Leather Pouch",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        rating: 4,
        price: 150.00,
        originalPrice: 170.00,
        images: [pizzaImage,pizzaImage],
        badge: 'sale',
    },
    {
        id: 7,
        category: 'watches',
        keyWords:['watches'],
        title: "Smart watche Vital Plus",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        rating: 3.5,
        price: 100.00,
        originalPrice: 120.00,
        images: [pizzaImage,pizzaImage],
    },
    {
        id: 8,
        category: 'party wear',
        keyWords:['party wear'],
        title: "Womens Party Wear Shoes",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        rating: 1.5,
        price: 25.00,
        originalPrice: 30.00,
        images: [pizzaImage,pizzaImage],
        badge: 'sale',
    },
    {
        id: 9,
        category: 'jacket',
        keyWords:['jacket'],
        title: "Mens Winter Leathers Jackets",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        rating: 3.5,
        price: 32.00,
        originalPrice: 45.00,
        images: [pizzaImage,pizzaImage],
        
    },
    {
        id: 10,
        category: 'sports',
        keyWords:['sports'],
        title: "Trekking & Running Shoes - black",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        rating: 3.5,
        price: 58.00,
        originalPrice: 64.00,
        images: [pizzaImage,pizzaImage],
        badge: 'sale',
    },
    {
        id: 11,
        category: 'formal',
        keyWords:['formal'],
        title: "Men's Leather Formal Wear shoes",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        rating: 3.5,
        price: 50.00,
        originalPrice: 65.00,
        images: [pizzaImage,pizzaImage],
        badge: 'sale',
    },
    {
        id: 12,
        category: 'shorts',
        keyWords:['shorts','formal'],
        title: "Better Basics French Terry Sweatshorts",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        rating: 3.5,
        price: 78.00,
        originalPrice: 85.00,
        images: [pizzaImage,pizzaImage],
        badge: 'sale',
    },
];
